#!/usr/bin/env bash
# MILNET threshold-KEK ceremony runner.
#
# Runs the KEK ceremony tool, then renders the k3s Secret manifests
# (milnet-kek-shares + milnet-vss-commitments). Run on a TRUSTED host.
#
# Usage:  run-ceremony.sh [threshold] [total] [out-dir]
#   defaults: threshold=3 total=5 out-dir=./kek-ceremony-out
#
# After running:
#   kubectl apply -f <out-dir>/milnet-kek-secrets.yaml   # or via Vault/ESO
#   shred -u <out-dir>/kek-share-*.hex                   # destroy local copies
set -euo pipefail

THRESHOLD="${1:-3}"
TOTAL="${2:-5}"
OUT="${3:-./kek-ceremony-out}"
REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
NS="${MILNET_NAMESPACE:-milnet}"

echo "[ceremony] threshold=${THRESHOLD} total=${TOTAL} out=${OUT}"

# ── 1. Generate shares + VSS commitments (master KEK never persisted) ────────
( cd "$REPO_ROOT" && cargo run --release --quiet \
    --example kek_ceremony -p common -- "$OUT" "$THRESHOLD" "$TOTAL" )

# ── 2. Render k3s Secret manifests ───────────────────────────────────────────
SECRET_FILE="$OUT/milnet-kek-secrets.yaml"
umask 077
{
  echo "# GENERATED by run-ceremony.sh — contains TOP SECRET key material."
  echo "# Apply, then destroy this file (shred -u)."
  echo "apiVersion: v1"
  echo "kind: Secret"
  echo "metadata:"
  echo "  name: milnet-kek-shares"
  echo "  namespace: ${NS}"
  echo "type: Opaque"
  echo "stringData:"
  for i in $(seq 1 "$TOTAL"); do
    echo "  share-${i}: \"$(cat "$OUT/kek-share-${i}.hex")\""
  done
  echo "---"
  echo "apiVersion: v1"
  echo "kind: Secret"
  echo "metadata:"
  echo "  name: milnet-vss-commitments"
  echo "  namespace: ${NS}"
  echo "type: Opaque"
  echo "stringData:"
  echo "  MILNET_VSS_COMMITMENTS: \"$(cat "$OUT/vss-commitments.hex")\""
} > "$SECRET_FILE"
chmod 600 "$SECRET_FILE"

echo "[ceremony] done."
echo "  shares + commitments : $OUT/"
echo "  k3s Secret manifest  : $SECRET_FILE"
echo
echo "NEXT:"
echo "  kubectl apply -f $SECRET_FILE"
echo "  shred -u $OUT/kek-share-*.hex $SECRET_FILE   # destroy local plaintext"
echo
echo "For production: load the shares into Vault and use the existing"
echo "deploy/kubernetes/external-secrets/ ExternalSecret objects instead of"
echo "applying raw Secret YAML."
