###############################################################################
# MILNET SSO — Demo Trial: Full Security on Free Trial Budget
#
# ARCHITECTURE SUMMARY:
#   Compute:   Single e2-medium SPOT VM (~$7.50/mo)
#              All 8 services + 5 FROST signers + 3 BFT audit as systemd units
#   Database:  Cloud SQL db-f1-micro PostgreSQL 16 ZONAL (~$7.67/mo)
#   Cache:     NONE — in-memory HashMap (<100 users/week doesn't need Redis)
#   KMS:       Cloud KMS SOFTWARE keys (~$0.12/mo vs $2/mo for HSM)
#   WAF:       NONE — app-layer puzzle + per-IP rate limiting is sufficient
#   Network:   Ephemeral IP (free) + firewall rules (free)
#   Secrets:   Secret Manager 3 secrets (~$0 free tier)
#   Observe:   Cloud Logging/Monitoring free tier only (~$0)
#
# ESTIMATED TOTAL: ~$16.30/mo = 18 months on $300 free trial credit
#
# QUANTUM-SAFE DESIGN (IDENTICAL TO PRODUCTION — same Rust binary):
#   All inter-service: SHARD protocol (HMAC-SHA512 + AES-256-GCM over mTLS 1.3)
#   Token signing: FROST 3-of-5 nested under ML-DSA-87 (FIPS 204)
#   Key exchange: X-Wing hybrid KEM (ML-KEM-1024 + X25519)
#   Session keys: HKDF-SHA512 ratcheting (forward secrecy)
#   Audit: ML-DSA-87 signed, SHA3-256 Merkle tree, BFT 3-node consensus
#   Passwords: OPAQUE RFC 9497 (server-blind, Argon2id)
#   Token binding: DPoP + ML-DSA-65 (stolen tokens unusable)
#
# KEY INSIGHT: Same binary = same crypto. Only infrastructure redundancy differs.
###############################################################################

terraform {
  required_version = ">= 1.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
  zone    = var.zone
}

# ---------------------------------------------------------------------------
# Data sources
# ---------------------------------------------------------------------------
data "google_project" "current" {
  project_id = var.project_id
}

locals {
  prefix = "milnet-demo"

  labels = {
    project     = "milnet-sso"
    environment = var.environment
    managed_by  = "terraform"
    cost_tier   = "free-trial"
  }
}

###############################################################################
# Enable Required GCP APIs (minimal set — no GKE, no Redis, no Trace)
###############################################################################

resource "google_project_service" "apis" {
  for_each = toset([
    "compute.googleapis.com",
    "sqladmin.googleapis.com",
    "cloudkms.googleapis.com",
    "secretmanager.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "servicenetworking.googleapis.com",
  ])

  project            = var.project_id
  service            = each.key
  disable_on_destroy = false
}

###############################################################################
# Random Passwords — Generated by Terraform, stored in Secret Manager
###############################################################################

resource "random_password" "db_password" {
  count   = var.db_password == "" ? 1 : 0
  length  = 80
  special = false
}

resource "random_password" "master_kek_seed" {
  length  = 64
  special = false
}

resource "random_password" "shard_hmac_key" {
  length  = 128
  special = false
}

locals {
  db_password = var.db_password != "" ? var.db_password : random_password.db_password[0].result
}

###############################################################################
# Secret Manager — 3 secrets (within free tier: 6 active versions free)
###############################################################################

resource "google_secret_manager_secret" "db_password" {
  secret_id = "${local.prefix}-db-password"
  project   = var.project_id
  labels    = local.labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = local.db_password
}

resource "google_secret_manager_secret" "master_kek_seed" {
  secret_id = "${local.prefix}-master-kek-seed"
  project   = var.project_id
  labels    = local.labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "master_kek_seed" {
  secret      = google_secret_manager_secret.master_kek_seed.id
  secret_data = random_password.master_kek_seed.result
}

resource "google_secret_manager_secret" "shard_hmac_key" {
  secret_id = "${local.prefix}-shard-hmac-key"
  project   = var.project_id
  labels    = local.labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "shard_hmac_key" {
  secret      = google_secret_manager_secret.shard_hmac_key.id
  secret_data = random_password.shard_hmac_key.result
}

###############################################################################
# Cloud KMS — Software-Protected Keys (Envelope Encryption)
#
# COST: SOFTWARE = $0.06/key/mo vs HSM = $1.00/key/mo
# SECURITY: Same AES-256-GCM envelope encryption, same key rotation.
# The app does ALL signing locally (ML-DSA/FROST). KMS only wraps the
# master KEK at startup (<10 ops/day). HSM is overkill for a demo.
###############################################################################

resource "google_kms_key_ring" "sso" {
  name     = "${local.prefix}-keyring"
  project  = var.project_id
  location = var.region

  depends_on = [google_project_service.apis]
}

resource "google_kms_crypto_key" "master_kek" {
  name     = "master-kek"
  key_ring = google_kms_key_ring.sso.id
  purpose  = "ENCRYPT_DECRYPT"

  version_template {
    algorithm        = "GOOGLE_SYMMETRIC_ENCRYPTION"
    protection_level = var.kms_protection_level
  }

  rotation_period = "7776000s" # 90 days — same as production

  labels = merge(local.labels, {
    key_purpose = "master-envelope-encryption"
  })
}

resource "google_kms_crypto_key" "backup_kek" {
  name     = "backup-kek"
  key_ring = google_kms_key_ring.sso.id
  purpose  = "ENCRYPT_DECRYPT"

  version_template {
    algorithm        = "GOOGLE_SYMMETRIC_ENCRYPTION"
    protection_level = var.kms_protection_level
  }

  rotation_period = "15552000s" # 180 days — same as production

  labels = merge(local.labels, {
    key_purpose = "backup-envelope-encryption"
  })
}

###############################################################################
# Networking — Default VPC + Firewall (minimal, no LB, no NAT)
#
# COST: $0 — uses default VPC, ephemeral IP (free), firewall rules (free)
# Only ports 9100 (gateway) and 8080 (admin) are exposed.
# VM has external IP so no Cloud NAT needed.
###############################################################################

resource "google_compute_firewall" "sso_services" {
  name    = "${local.prefix}-allow-services"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["9100", "443", "80"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["milnet-demo"]
}

resource "google_compute_firewall" "sso_admin" {
  name    = "${local.prefix}-allow-admin"
  network = "default"

  allow {
    protocol = "tcp"
    ports    = ["8080"]
  }

  # Admin panel: restrict to known IPs in production. Open for demo.
  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["milnet-demo"]
}

resource "google_compute_firewall" "sso_iap_ssh" {
  name     = "${local.prefix}-allow-iap-ssh"
  network  = "default"
  priority = 800

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  # IAP tunnel range — SSH only through Identity-Aware Proxy
  source_ranges = ["35.235.240.0/20"]
  target_tags   = ["milnet-demo"]
}

###############################################################################
# Cloud SQL — PostgreSQL 16 (db-f1-micro, ZONAL, HDD)
#
# COST: ~$7.67/mo (shared core, 0.6 GB RAM, 10 GB HDD)
# SECURITY: Private IP only + SSL required (same as production)
# NO HA — single zone, daily backups only (acceptable for demo)
###############################################################################

resource "google_compute_global_address" "private_services" {
  name          = "${local.prefix}-private-svc"
  project       = var.project_id
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = "projects/${var.project_id}/global/networks/default"
}

resource "google_service_networking_connection" "private_services" {
  network                 = "projects/${var.project_id}/global/networks/default"
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private_services.name]

  depends_on = [google_project_service.apis]
}

resource "google_sql_database_instance" "primary" {
  name                = "${local.prefix}-db"
  project             = var.project_id
  region              = var.region
  database_version    = "POSTGRES_16"
  deletion_protection = false # Demo — allow easy teardown

  settings {
    tier              = var.db_tier
    edition           = "ENTERPRISE"
    availability_type = "ZONAL" # No HA — demo only, saves ~$7.67/mo
    disk_size         = var.db_disk_size
    disk_type         = "PD_HDD" # HDD not SSD — cost optimization for demo
    disk_autoresize   = false    # Fixed 10 GB — predictable cost

    ip_configuration {
      ipv4_enabled                                  = false # Private IP only
      private_network                               = "projects/${var.project_id}/global/networks/default"
      enable_private_path_for_google_cloud_services = true
      require_ssl                                   = true
      ssl_mode                                      = "ENCRYPTED_ONLY"
    }

    backup_configuration {
      enabled    = true
      start_time = "03:00"
      # No PITR — demo doesn't need point-in-time recovery
      backup_retention_settings {
        retained_backups = 3 # Keep 3 days (vs 14 in production)
        retention_unit   = "COUNT"
      }
    }

    database_flags {
      name  = "max_connections"
      value = "50" # Plenty for <100 users/week
    }

    database_flags {
      name  = "log_connections"
      value = "on"
    }

    database_flags {
      name  = "log_disconnections"
      value = "on"
    }

    user_labels = local.labels
  }

  depends_on = [google_service_networking_connection.private_services]
}

resource "google_sql_database" "sso" {
  name     = "milnet_sso"
  project  = var.project_id
  instance = google_sql_database_instance.primary.name
}

resource "google_sql_user" "workload" {
  name     = "milnet"
  project  = var.project_id
  instance = google_sql_database_instance.primary.name
  password = local.db_password
}

###############################################################################
# IAM — Service Account for VM (minimal privileges)
###############################################################################

resource "google_service_account" "vm_workload" {
  account_id   = "${local.prefix}-workload"
  project      = var.project_id
  display_name = "MILNET SSO Demo Trial VM Workload"
}

resource "google_project_iam_member" "vm_kms" {
  project = var.project_id
  role    = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member  = "serviceAccount:${google_service_account.vm_workload.email}"
}

resource "google_project_iam_member" "vm_secrets" {
  project = var.project_id
  role    = "roles/secretmanager.secretAccessor"
  member  = "serviceAccount:${google_service_account.vm_workload.email}"
}

resource "google_project_iam_member" "vm_logging" {
  project = var.project_id
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${google_service_account.vm_workload.email}"
}

resource "google_project_iam_member" "vm_monitoring" {
  project = var.project_id
  role    = "roles/monitoring.metricWriter"
  member  = "serviceAccount:${google_service_account.vm_workload.email}"
}

###############################################################################
# Compute Engine — Single e2-medium SPOT VM
#
# COST: ~$7.50/mo (SPOT = 60-91% off on-demand)
# 1 shared vCPU, 4 GB RAM — enough for <100 users/week
#
# ALL 8 services + 5 FROST signers + 3 BFT audit nodes run as systemd units.
# Same Rust binary, different configs on different ports.
# SHARD mTLS still works over localhost — same protocol, same security.
###############################################################################

resource "google_compute_instance" "sso_demo" {
  name         = "${local.prefix}-vm"
  machine_type = var.vm_machine_type
  zone         = var.zone

  tags = ["milnet-demo"]

  scheduling {
    preemptible                 = true
    automatic_restart           = false
    provisioning_model          = "SPOT"
    instance_termination_action = "STOP"
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
      size  = 30
      type  = "pd-standard" # Standard HDD — cheapest boot disk
    }
  }

  network_interface {
    network = "default"

    access_config {
      # Ephemeral IP — free (no static IP reservation)
    }
  }

  metadata = {
    github-repo        = var.github_repo
    frost-signer-count = var.frost_signer_count
    bft-audit-nodes    = var.bft_audit_node_count
    db-private-ip      = google_sql_database_instance.primary.private_ip_address
    db-password-secret = google_secret_manager_secret.db_password.secret_id
    kek-seed-secret    = google_secret_manager_secret.master_kek_seed.secret_id
    shard-hmac-secret  = google_secret_manager_secret.shard_hmac_key.secret_id
    kms-key-id         = google_kms_crypto_key.master_kek.id
  }

  metadata_startup_script = file("${path.module}/startup.sh")

  service_account {
    email = google_service_account.vm_workload.email
    scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }

  labels = local.labels

  allow_stopping_for_update = true

  depends_on = [
    google_project_service.apis,
    google_sql_database_instance.primary,
    google_sql_user.workload,
    google_secret_manager_secret_version.db_password,
    google_secret_manager_secret_version.master_kek_seed,
    google_secret_manager_secret_version.shard_hmac_key,
  ]
}
