---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: milnet-tss-share-0
  namespace: milnet
spec:
  refreshInterval: "1h"
  secretStoreRef: { name: vault-milnet-prod, kind: ClusterSecretStore }
  target: { name: milnet-tss-share-0, creationPolicy: Owner }
  data:
    - secretKey: MILNET_TSS_SHARE_SEALED
      remoteRef: { key: milnet/prod/tss-shares, property: share_0 }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: milnet-tss-share-1
  namespace: milnet
spec:
  refreshInterval: "1h"
  secretStoreRef: { name: vault-milnet-prod, kind: ClusterSecretStore }
  target: { name: milnet-tss-share-1, creationPolicy: Owner }
  data:
    - secretKey: MILNET_TSS_SHARE_SEALED
      remoteRef: { key: milnet/prod/tss-shares, property: share_1 }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: milnet-tss-share-2
  namespace: milnet
spec:
  refreshInterval: "1h"
  secretStoreRef: { name: vault-milnet-prod, kind: ClusterSecretStore }
  target: { name: milnet-tss-share-2, creationPolicy: Owner }
  data:
    - secretKey: MILNET_TSS_SHARE_SEALED
      remoteRef: { key: milnet/prod/tss-shares, property: share_2 }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: milnet-tss-share-3
  namespace: milnet
spec:
  refreshInterval: "1h"
  secretStoreRef: { name: vault-milnet-prod, kind: ClusterSecretStore }
  target: { name: milnet-tss-share-3, creationPolicy: Owner }
  data:
    - secretKey: MILNET_TSS_SHARE_SEALED
      remoteRef: { key: milnet/prod/tss-shares, property: share_3 }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: milnet-tss-share-4
  namespace: milnet
spec:
  refreshInterval: "1h"
  secretStoreRef: { name: vault-milnet-prod, kind: ClusterSecretStore }
  target: { name: milnet-tss-share-4, creationPolicy: Owner }
  data:
    - secretKey: MILNET_TSS_SHARE_SEALED
      remoteRef: { key: milnet/prod/tss-shares, property: share_4 }
