---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: milnet-pq-signing-keys
  namespace: milnet
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-milnet-prod
    kind: ClusterSecretStore
  target:
    name: milnet-pq-signing-keys
    creationPolicy: Owner
  data:
    - secretKey: MILNET_PQ_VERIFYING_KEY
      remoteRef:
        key: milnet/prod/pq-signing
        property: ml_dsa_public
    - secretKey: MILNET_PQ_SIGNING_KEY_SEALED
      remoteRef:
        key: milnet/prod/pq-signing
        property: ml_dsa_private_sealed
    - secretKey: MILNET_SLHDSA_VERIFYING_KEY
      remoteRef:
        key: milnet/prod/pq-signing
        property: slh_dsa_public
    - secretKey: MILNET_SLHDSA_SIGNING_KEY_SEALED
      remoteRef:
        key: milnet/prod/pq-signing
        property: slh_dsa_private_sealed
