---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-milnet-prod
spec:
  provider:
    vault:
      server: "https://vault.milnet.internal:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: ConfigMap
        name: vault-ca
        namespace: external-secrets
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "milnet-prod-reader"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
